version: '3.7'

services:

  app:
    build:
      context: .
      dockerfile: .docker/Dockerfile
    image: 'university'
    # user: root
    working_dir: /var/www/html
    container_name: university
    restart: unless-stopped
    # depends_on:
    #   - db
    ports:
      - "8100:80"
    volumes:
      - ./:/var/www/html
    networks:
      external:

networks:
    # mysql8_mynetwork:
        # driver: bridge
    external:
      name: mysql8_mynetwork
