version: '3.7'

services:

  app:
    build:
      context: .
      dockerfile: .docker/Dockerfile
    image: 'university'
    # user: root
    working_dir: /var/www/html
    container_name: university
    restart: unless-stopped
    # depends_on:
    #   - db
    ports:
      - "8100:80"
    volumes:
      - ./:/var/www/html
    networks:
      default:

#   db:
#     image:  mysql8
#     container_name: checkingnet-mysql
#     restart: always
#     ports:
#       - "3306:3306"
#     environment:
#       MYSQL_DATABASE: 'supportdb'
#       MYSQL_USER: 'root'
#       MYSQL_ALLOW_EMPTY_PASSWORD: 1
#       MYSQL_ROOT_PASSWORD: "secret"
#     volumes:
#       - mysql-volume:/var/lib/mysql
#     networks:
#       default:

# volumes:
#   mysql-volume:
#     external: true

networks:
  default:
    external:
      name: mynet
